import "~/styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Karla as FontSans } from "next/font/google";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const fontSans = FontSans({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  style: "normal",
  variable: "--font-karla",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${fontSans.variable} --font-karla dark`}>
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
